# Generated by Django 2.2.9 on 2020-03-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AditivosNutritivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('formula_quimica', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'aditivos_nutritivos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AditivosNutritivosPicole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'aditivos_nutritivos_picole',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Conservantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('descricao', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'conservantes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConservantesPicoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'conservantes_picoles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'ingredientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IngredientesPicole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ingredientes_picole',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
            ],
            options={
                'db_table': 'lotes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LotesNotaFiscal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'lotes_nota_fiscal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotasFiscais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('numero_serie', models.CharField(max_length=45)),
                ('descricao', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'notas_fiscais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Picoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'picoles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Revendedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=45)),
                ('razao_social', models.CharField(max_length=100)),
                ('contato', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'revendedores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sabores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'sabores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposEmbalagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': ' Tipos Embalagem',
                'verbose_name_plural': ' Tipos Embalagens',
                'db_table': 'tipos_embalagem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposPicole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tipos_picole',
                'managed': False,
            },
        ),
    ]
